### ISSUE TITLE
Agenda doesn't work properly in Firefox 57.0.3 (64-bit) 

### ISSUE THREAD

**Issue by janczer** [zerocracy/datum#189] opened 2018-01-09 11:43 UTC
![bug_0crat](https://user-images.githubusercontent.com/13544213/34719204-21c933be-f53a-11e7-9662-039b9825f9f1.png)

Here code from Firefox inspector:

```
<article>&lt;body xmlns="http://www.w3.org/1999/xhtml"&gt;
   &lt;section&gt;
      &lt;h1&gt;Your Agenda&lt;/h1&gt;
      &lt;p&gt;This is the full list of 2 jobs currently assigned to you
            in all projects we are managing. Zerocrat adds jobs here
            automatically. This list is presented for the sake of
            your convenience.&lt;/p&gt;
      &lt;table&gt;
         &lt;thead&gt;
            &lt;tr&gt;
               &lt;th&gt;Job&lt;/th&gt;
               &lt;th&gt;Project&lt;/th&gt;
               &lt;th&gt;Added&lt;/th&gt;
            &lt;/tr&gt;
         &lt;/thead&gt;
         &lt;tbody&gt;
            &lt;tr&gt;
               &lt;td&gt;
                  &lt;a href="https://github.com/yegor256/jpeek/issues/85"
                     title="Issue #85 in yegor256/jpeek GitHub repository"&gt;yegor256/jpeek#85&lt;/a&gt;
               &lt;/td&gt;
               &lt;td&gt;
                  &lt;code&gt;
                     &lt;a href="http://www.0crat.com/p/C7JGJ00DP" title="Project C7JGJ00DP"&gt;C7JGJ00DP&lt;/a&gt;
                  &lt;/code&gt;
               &lt;/td&gt;
               &lt;td&gt;
                  &lt;span title="2018-01-09T10:30:43.035Z"&gt;1 hours ago&lt;/span&gt;
               &lt;/td&gt;
            &lt;/tr&gt;
            &lt;tr&gt;
               &lt;td&gt;
                  &lt;a href="https://github.com/yegor256/jpeek/issues/52"
                     title="Issue #52 in yegor256/jpeek GitHub repository"&gt;yegor256/jpeek#52&lt;/a&gt;
               &lt;/td&gt;
               &lt;td&gt;
                  &lt;code&gt;
                     &lt;a href="http://www.0crat.com/p/C7JGJ00DP" title="Project C7JGJ00DP"&gt;C7JGJ00DP&lt;/a&gt;
                  &lt;/code&gt;
               &lt;/td&gt;
               &lt;td&gt;
                  &lt;span title="2018-01-09T09:29:02.781Z"&gt;2 hours ago&lt;/span&gt;
               &lt;/td&gt;
            &lt;/tr&gt;
         &lt;/tbody&gt;
      &lt;/table&gt;
   &lt;/section&gt;
&lt;/body&gt;</article>
```

Firefox Quantum 57.0.3 (64-bit)
Linux Mint 18.2 Cinnamon 64-bit

**Comment by 0crat** [comment] 2018-01-09 11:43
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment] 2018-01-30 15:46
Job [#189](https://github.com/zerocracy/datum/issues/189) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-02-21 13:29
The job [#189](https://github.com/zerocracy/datum/issues/189) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/521329481). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment] 2018-02-26 13:30
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2018-03-01 13:30
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment] 2018-03-02 18:38
@0crat refuse

**Comment by 0crat** [comment] 2018-03-02 18:39
> @0crat refuse ([here](https://github.com/zerocracy/datum/issues/189#issuecomment-370013287))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#189](https://github.com/zerocracy/datum/issues/189), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-03-02 18:40
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment] 2018-03-06 15:59
The job [#189](https://github.com/zerocracy/datum/issues/189) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/651559205). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment] 2018-03-08 12:34
@0crat refuse

**Comment by 0crat** [comment] 2018-03-08 12:47
> @0crat refuse ([here](https://github.com/zerocracy/datum/issues/189#issuecomment-371474396))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#189](https://github.com/zerocracy/datum/issues/189), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-03-08 12:48
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by t-izbassar** [comment] 2018-03-16 18:44
@yegor256 this issue is a duplicate of the [402](https://github.com/zerocracy/farm/issues/402). I think you should close one of them so that not to pay twice for the same job.

**Comment by yegor256** [comment] 2018-03-16 19:41
@0crat refuse

**Comment by 0crat** [comment] 2018-03-16 19:41
> @0crat refuse ([here](https://github.com/zerocracy/datum/issues/189#issuecomment-373824041))

@yegor256 The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#189](https://github.com/zerocracy/datum/issues/189), please stop working. Reason for job resignation: Order was cancelled

**Closed** 2018-03-16 19:42 UTC
Labels: bug, duplicate, scope

**Comment by 0crat** [comment] 2018-03-20 16:25
The job [#189](https://github.com/zerocracy/datum/issues/189) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/791636125); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by neonailol** [comment] 2018-03-20 16:51
@yegor256 can you unlink me from this task?

**Comment by 0crat** [comment] 2018-03-22 08:32
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @neonailol[/z](https://www.0crat.com/u/neonailol), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2018-03-22 08:32
The job [#189](https://github.com/zerocracy/datum/issues/189) is now out of scope

**Comment by ypshenychka** [comment] 2018-03-22 08:45
@0crat quality bad

**Comment by 0crat** [comment] 2018-03-22 08:45
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment] 2018-03-22 08:45
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by yegor256** [comment] 2018-03-22 10:10
@0crat status

**Comment by 0crat** [comment] 2018-03-22 10:11
> @0crat status ([here](https://github.com/zerocracy/datum/issues/189#issuecomment-375244230))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#189](https://github.com/zerocracy/datum/issues/189) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Fdatum%23189%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
